<a href="https://colab.research.google.com/github/Yuvankishore448/python-with-machine-learning/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,6,4])
print(arr)
x=np.where(arr==4)
print(x)

[1 2 3 4 5 4 6 4]
(array([3, 5, 7]),)


In [ ]:
#indexes where the values are even
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr % 2 == 0)
print(arr)
print(x)

[1 2 3 4 5 6 7 8]
(array([1, 3, 5, 7]),)


In [ ]:
#sorting the array
import numpy as np
arr = np.array([3,1,0,2])
print("\nOriginal array:",arr)
print("\nSorted array:",np.sort(arr))
arr = np.array([[1,2,4], [5,0,1]])
print("\nOriginal 2D array:",arr)
print("\nSorted 2D array:",np.sort(arr))


Original array: [3 1 0 2]

Sorted array: [0 1 2 3]

Original 2D array: [[1 2 4]
 [5 0 1]]

Sorted 2D array: [[1 2 4]
 [0 1 5]]


In [ ]:
import numpy as np
sorted_array=np.array([1,3,5,7])
values=(2,4,8)
insert_indices=np.searchsorted(sorted_array,values)
print(sorted_array)
print (values)
print (insert_indices)

[1 3 5 7]
(2, 4, 8)
[1 2 4]


In [ ]:
#filter
arr = np.array([41, 42, 43, 44])
x=[True, False, True, False]
newarr=arr[x]
print("\nOriginal array:", arr)
print("\nFilter array:",x)
print("\nFiltered array:",newarr)


Original array: [41 42 43 44]

Filter array: [True, False, True, False]

Filtered array: [41 43]


In [ ]:
arr = np.array([41, 42, 43, 44])
filter_arr=arr>42
newarr=arr[x]
print("\noriginal array:", arr)
print("\nFilter array:condition->42", filter_arr)
print("\nNew array:",newarr)


original array: [41 42 43 44]

Filter array:condition->42 [False False  True  True]

New array: [41 43]
